version: '3.8'

services:
  backend:
    build:
      context: ./interface
    container_name: mqtt-interface
    environment:
      - MONGO_URI=mongodb://db:27017/
    depends_on:
      - db
    networks:
      - vineyard-network
  db:
    image: mongo:latest
    container_name: vineyard-db
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"  
    networks:
      - vineyard-network

volumes:
  db_data:
    driver: local

networks:
  vineyard-network:
    driver: bridge

